### ISSUE TITLE
Error in "scripts/EXP-LongForecasting/Linear/univariate/etth2.sh"

### ISSUE THREAD

**Issue by xiao-he** [cure-lab/LTSF-Linear#53]
There is an error while running univariate exp as shown in the following

(LTSF_Linear) user:~/LTSF-Linear-main$ sh scripts/EXP-LongForecasting/Linear/univariate/etth2.sh
Traceback (most recent call last):
  File "run_longExp.py", line 120, in <module>
    exp.train(setting)
  File "/user/LTSF-Linear-main/exp/exp_main.py", line 100, in train
    train_data, train_loader = self._get_data(flag='train')
  File "/user/LTSF-Linear-main/exp/exp_main.py", line 42, in _get_data
    data_set, data_loader = data_provider(self.args, flag)
  File "/user/LTSF-Linear-main/data_provider/data_factory.py", line 44, in data_provider
    train_only=train_only
TypeError: __init__() got an unexpected keyword argument 'train_only'

**Comment by wangsheng1991** [comment]
I think you can arrange your code first

**Comment by xiao-he** [comment]
Do you have a clue on how to arrange the code?

The one for exchange_rate works for me 
"sh scripts/EXP-LongForecasting/Linear/exchange_rate.sh"

But the one with etth1 makes the above error
"sh scripts/EXP-LongForecasting/Linear/etth1.sh"

File "/user/LTSF-Linear-main/data_provider/data_factory.py", line 44, in data_provider
train_only=train_only
TypeError: init() got an unexpected keyword argument 'train_only'

**Comment by mixiancmx** [comment]
Sorry, it is fixed now.

**Comment by xiao-he** [comment]
> Sorry, it is fixed now.

Thanks, it works now.
