### ISSUE TITLE
Error ValueError: __len__() should return >= 0

### ISSUE THREAD

**Issue by Med-Rokaimi** [cure-lab/LTSF-Linear#82]
I created my own sh file to run on my own dataset (4 features including the target) and I got this error
File "LTSF-Linear/exp/exp_main.py", line 42, in _get_data
    data_set, data_loader = data_provider(self.args, flag)  File "LTSF-Linear/data_provider/data_factory.py", line 46, in data_provider
    print(flag, len(data_set))
ValueError: __len__() should return >= 0
Traceback (most recent call last):

**Comment by mixiancmx** [comment]
Maybe you can make your dataset have the same format as the existing dataset.

**Comment by vascojesus** [comment]
Hi!
I'm getting the same error explained above - also created my own .sh and tried to have a dataset with the same format as the datasets shown. Could someone clarify on the dataset format?
Thanks!

**Comment by jcrucesdeveloper** [comment]
Maybe you can make your code extensible to different formats!!! :)
